"""Initial migration

Revision ID: 75668096e911
Revises: 
Create Date: 2026-02-13 11:12:51.076769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75668096e911'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模型名称(中文)'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='模型代码(英文)'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='模型描述'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='模型分类: room/cabinet/device/port/fiber等'),
    sa.Column('icon', sa.String(length=100), nullable=True, comment='图标标识'),
    sa.Column('color', sa.String(length=20), nullable=True, comment='显示颜色'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('is_system', sa.Boolean(), nullable=True, comment='是否系统内置模型'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('regions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='区域名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='区域编码'),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='父级区域ID'),
    sa.Column('level', sa.Enum('PROVINCE', 'CITY', 'DISTRICT', 'PLANNING_AREA', name='regionlevel'), nullable=False, comment='区域层级'),
    sa.Column('area_type', sa.Enum('IMPORTANT_AGG', 'INTEGRATED_SERVICE', 'RURAL_HOTSPOT', name='areatype'), nullable=True, comment='区域类型(仅规划区使用): IMPORTANT_AGG/INTEGRATED_SERVICE/RURAL_HOTSPOT'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='区域描述'),
    sa.Column('planned_room_count', sa.Integer(), nullable=True, comment='规划机房数量'),
    sa.Column('actual_room_count', sa.Integer(), nullable=True, comment='实际机房数量'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('attributes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='属性名称(英文键)'),
    sa.Column('label', sa.String(length=100), nullable=False, comment='属性标签(中文显示名)'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='属性描述'),
    sa.Column('type', sa.Enum('STRING', 'NUMBER', 'ENUM', 'BOOLEAN', 'DATE', 'DATETIME', 'JSON', 'UUID', name='attributetype'), nullable=False, comment='数据类型'),
    sa.Column('is_required', sa.Boolean(), nullable=True, comment='是否必填'),
    sa.Column('is_unique', sa.Boolean(), nullable=True, comment='是否唯一'),
    sa.Column('is_indexed', sa.Boolean(), nullable=True, comment='是否索引'),
    sa.Column('is_readonly', sa.Boolean(), nullable=True, comment='是否只读'),
    sa.Column('default_value', sa.Text(), nullable=True, comment='默认值'),
    sa.Column('enum_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="枚举值列表: ['value1', 'value2']"),
    sa.Column('validation_regex', sa.String(length=500), nullable=True, comment='正则校验规则'),
    sa.Column('min_value', sa.String(length=50), nullable=True, comment='最小值(数字/日期)'),
    sa.Column('max_value', sa.String(length=50), nullable=True, comment='最大值(数字/日期)'),
    sa.Column('sort_order', sa.String(length=10), nullable=True, comment='排序序号'),
    sa.Column('group_name', sa.String(length=50), nullable=True, comment='属性分组名称'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attributes_model_name', 'attributes', ['model_id', 'name'], unique=False)
    op.create_table('instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False, comment='关联模型ID'),
    sa.Column('region_id', sa.UUID(), nullable=True, comment='关联区域ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='实例名称'),
    sa.Column('code', sa.String(length=100), nullable=True, comment='实例编码'),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='动态属性数据(JSONB)'),
    sa.Column('status', sa.Enum('PLANNING', 'CONSTRUCTION', 'ACTIVE', 'RETIRED', name='instancestatus'), nullable=True, comment='生命周期状态: planning/construction/active/retired'),
    sa.Column('evolution_type', sa.Enum('TARGET', 'ANCHOR', name='evolutiontype'), nullable=True, comment='演进标识: TARGET(目标)/ANCHOR(锚点)'),
    sa.Column('description', sa.Text(), nullable=True, comment='实例描述'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='更新人'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_instances_code', 'instances', ['code'], unique=False)
    op.create_index('ix_instances_data_gin', 'instances', ['data'], unique=False, postgresql_using='gin')
    op.create_index('ix_instances_model_id', 'instances', ['model_id'], unique=False)
    op.create_index('ix_instances_name', 'instances', ['name'], unique=False)
    op.create_index('ix_instances_region_id', 'instances', ['region_id'], unique=False)
    op.create_index('ix_instances_status', 'instances', ['status'], unique=False)
    op.create_table('lifecycle_milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False, comment='关联实例ID'),
    sa.Column('milestone_key', sa.Enum('PROJECT_APPROVAL', 'PROCUREMENT_DECISION', 'RECEIPT', 'CERTIFICATE', 'DESIGN_SURVEY', 'DESIGN_APPROVAL', 'MATERIALS_ARRIVAL', 'CONSTRUCTION', 'EXTERNAL_POWER', 'DECORATION', 'EQUIPMENT_INSTALL', 'PIPELINE', 'CIRCUIT', 'COMPLETION', 'GO_LIVE', name='milestonekey'), nullable=False, comment='里程碑类型'),
    sa.Column('phase', sa.Enum('INITIATION', 'PROCUREMENT', 'DESIGN', 'CONSTRUCTION', 'FACILITY', 'COMPLETION', name='milestonephase'), nullable=False, comment='建设阶段'),
    sa.Column('milestone_name', sa.String(length=100), nullable=False, comment='里程碑名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='里程碑描述'),
    sa.Column('planned_start_date', sa.Date(), nullable=True, comment='计划开始日期'),
    sa.Column('planned_end_date', sa.Date(), nullable=True, comment='计划结束日期'),
    sa.Column('actual_start_date', sa.Date(), nullable=True, comment='实际开始日期'),
    sa.Column('actual_end_date', sa.Date(), nullable=True, comment='实际结束日期'),
    sa.Column('duration_days', sa.Integer(), nullable=True, comment='持续时间(天)'),
    sa.Column('status', sa.Enum('PENDING', 'ONGOING', 'COMPLETED', 'DELAYED', 'CANCELLED', name='milestonestatus'), nullable=True, comment='状态: PENDING/ONGOING/COMPLETED/DELAYED/CANCELLED'),
    sa.Column('progress', sa.Integer(), nullable=True, comment='进度百分比(0-100)'),
    sa.Column('responsible_person', sa.String(length=100), nullable=True, comment='负责人'),
    sa.Column('responsible_dept', sa.String(length=100), nullable=True, comment='责任部门'),
    sa.Column('remarks', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序序号'),
    sa.Column('is_critical_path', sa.Boolean(), nullable=True, comment='是否关键路径'),
    sa.Column('dependencies', sa.String(length=200), nullable=True, comment='依赖里程碑(逗号分隔)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lifecycle_milestones_instance_id', 'lifecycle_milestones', ['instance_id'], unique=False)
    op.create_index('ix_lifecycle_milestones_milestone_key', 'lifecycle_milestones', ['milestone_key'], unique=False)
    op.create_index('ix_lifecycle_milestones_phase', 'lifecycle_milestones', ['phase'], unique=False)
    op.create_index('ix_lifecycle_milestones_planned_end_date', 'lifecycle_milestones', ['planned_end_date'], unique=False)
    op.create_index('ix_lifecycle_milestones_status', 'lifecycle_milestones', ['status'], unique=False)
    op.create_table('relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False, comment='源实例ID'),
    sa.Column('target_id', sa.UUID(), nullable=False, comment='目标实例ID'),
    sa.Column('relation_type', sa.Enum('CONTAIN', 'CONNECT', 'CARRY', 'ASSOCIATE', 'BELONGS_TO_REGION', 'PARENT_CHILD', 'UPSTREAM_DOWNSTREAM', 'PRIMARY_BACKUP', name='relationtype'), nullable=False, comment='关系类型: contain/connect/carry/associate等'),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='关系属性: 如连接端口、带宽等'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='关系描述'),
    sa.Column('is_bidirectional', sa.String(length=10), nullable=True, comment='是否双向关系'),
    sa.Column('weight', sa.String(length=10), nullable=True, comment='关系权重'),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True, comment='生效开始时间'),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True, comment='生效结束时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建人'),
    sa.CheckConstraint('source_id != target_id', name='no_self_relation'),
    sa.ForeignKeyConstraint(['source_id'], ['instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_relations_relation_type', 'relations', ['relation_type'], unique=False)
    op.create_index('ix_relations_source_id', 'relations', ['source_id'], unique=False)
    op.create_index('ix_relations_source_target', 'relations', ['source_id', 'target_id'], unique=False)
    op.create_index('ix_relations_target_id', 'relations', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_relations_target_id', table_name='relations')
    op.drop_index('ix_relations_source_target', table_name='relations')
    op.drop_index('ix_relations_source_id', table_name='relations')
    op.drop_index('ix_relations_relation_type', table_name='relations')
    op.drop_table('relations')
    op.drop_index('ix_lifecycle_milestones_status', table_name='lifecycle_milestones')
    op.drop_index('ix_lifecycle_milestones_planned_end_date', table_name='lifecycle_milestones')
    op.drop_index('ix_lifecycle_milestones_phase', table_name='lifecycle_milestones')
    op.drop_index('ix_lifecycle_milestones_milestone_key', table_name='lifecycle_milestones')
    op.drop_index('ix_lifecycle_milestones_instance_id', table_name='lifecycle_milestones')
    op.drop_table('lifecycle_milestones')
    op.drop_index('ix_instances_status', table_name='instances')
    op.drop_index('ix_instances_region_id', table_name='instances')
    op.drop_index('ix_instances_name', table_name='instances')
    op.drop_index('ix_instances_model_id', table_name='instances')
    op.drop_index('ix_instances_data_gin', table_name='instances', postgresql_using='gin')
    op.drop_index('ix_instances_code', table_name='instances')
    op.drop_table('instances')
    op.drop_index('ix_attributes_model_name', table_name='attributes')
    op.drop_table('attributes')
    op.drop_table('regions')
    op.drop_table('models')
    # ### end Alembic commands ###
